platform:ios,'9.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
target 'factory' do
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'CRZXYCategory'
pod 'AFNetworking'
pod 'SDWebImage','~>4.0'
pod 'SVProgressHUD'
pod 'CYLTabBarController', '~> 1.17.4'
pod 'IQKeyboardManager'
pod 'AliyunOSSiOS'
pod 'Bugly'
pod 'AlicloudPush', '~> 1.9.8'
pod 'WechatOpenSDK' 
pod 'WeiboSDK'
pod 'BaiduMobStat'
pod 'SocketRocket'
pod 'TZImagePickerController'
end
